### ISSUE TITLE
/etc/sysconfig/varnish does not exist on many systems

### ISSUE THREAD

**Issue by rillip3** [unixy/varnishtuner.py#6]
On CentOS 7 (and presumably newer) and all Ubuntu systems lack an /etc/sysconfig/varnish file when installing from the system respository. In the case of Ubuntu I installed from the Varnish repo as well (there is no /etc/sysconfig at all on Ubuntu).  I'm not sure what this file is being scanned for, but it produces a fatal error when the file does not exist:

Traceback (most recent call last):
File "varnishtuner.py", line 532, in <module>
if not is_optsfile_sane(options_file):
File "varnishtuner.py", line 482, in is_optsfile_sane
f = open(file, "r")
IOError: [Errno 2] No such file or directory: '/etc/sysconfig/varnish'

**Comment by unixy** [comment]
Use: python varnishtuner -o /path/to/varnishoptions/file

**Comment by oppianmatt** [comment]
What is a varnish options file?

Ubuntu uses a /etc/default/varnish file but it doesn't work:

```
cat /etc/default/varnish
# Configuration file for varnish
#
# /etc/init.d/varnish expects the variables $DAEMON_OPTS, $NFILES and $MEMLOCK
# to be set from this shell script fragment.
#
# Note: If systemd is installed, this file is obsolete and ignored.  You will
# need to copy /lib/systemd/system/varnish.service to /etc/systemd/system/ and
# edit that file.

# Should we start varnishd at boot?  Set to "no" to disable.
START=yes

# Maximum number of open files (for ulimit -n)
NFILES=131072

# Maximum locked memory size (for ulimit -l)
# Used for locking the shared memory log in memory.  If you increase log size,
# you need to increase this number as well
MEMLOCK=122000

# Default varnish instance name is the local nodename.  Can be overridden with
# the -n switch, to have more instances on a single server.
# INSTANCE=$(uname -n)

# This file contains 4 alternatives, please use only one.



## Alternative 4, Do It Yourself

DAEMON_OPTS="-a :81 \
             -T :82 \
             -f /etc/varnish/default.vcl \
             -S /etc/varnish/secret \
             -s malloc,1G \
             "
```

Produces:

```
Traceback (most recent call last):
  File "varnishtuner.py", line 577, in <module>
    VC = VarnishConfig(options_file)
  File "varnishtuner.py", line 192, in __init__
    self.memorySetting = self.getMemorySetting(self.all_options_text)
  File "varnishtuner.py", line 265, in getMemorySetting
    mem_str = i.split(',')[2].strip('"')
IndexError: list index out of range
```
