### ISSUE TITLE
Index out of range on CentOS 6

### ISSUE THREAD

**Issue by rillip3** [unixy/varnishtuner.py#7]
After Issue #6 I tried the script on a CentOS 6 installation from the repo and got this:

[root@philip ~]# python varnishtuner.py 
The field 'n_wrk_lqueue' is not a valid field
usage: varnishstat [-1lV] [-f field_list] [-n varnish_name] [-w delay]
    -1                           # Print the statistics once and exit
    -f field_list                # Comma separated list of fields to display. 
                                 # If it starts with '^' it is used as an exclusion list
    -l                           # Lists the available fields to use with the -f option
    -n varnish_name              # The varnishd instance to get logs from
    -V                           # Display the version number and exit
    -w delay                     # Wait delay seconds between updates.  The default is 1.
    -x                           # Print statistics once as XML and exit.
Traceback (most recent call last):
  File "varnishtuner.py", line 541, in <module>
    VC = VarnishConfig(options_file)
  File "varnishtuner.py", line 183, in **init**
    self.memorySetting = self.getMemorySetting(self.all_options_text)
  File "varnishtuner.py", line 256, in getMemorySetting
    mem_str = i.split(',')[2].strip('"')
IndexError: list index out of range

**Comment by lmancilla** [comment]
+1 Ubuntu 14.04 LTS

**Comment by unixy** [comment]
Are you on varnish 3.x or 4.x?

**Comment by alxzndr** [comment]
+1 on ubuntu 14.04ltw with varnish-4.0.3 revision b8c4a34

**Comment by baurmatt** [comment]
+1 on Ubuntu 14.04 LTS with Varnish-Plus 4.0.3r3-3~trusty

**Comment by unixy** [comment]
Only Varnish 3.x was tested. Varnish 4.x is next.

**Comment by IhabY** [comment]
+1 CentOS 6 - varnish-3.0.7
