### ISSUE TITLE
Errors on two different servers

### ISSUE THREAD

**Issue by rdetwiler** [unixy/varnishtuner.py#8]
[root@mahoning ~]# python varnishtuner.py
        |>>     Varnish is offline! I'm beta crazy today so I'll continue...
Traceback (most recent call last):
  File "varnishtuner.py", line 515, in <module>
    varnish_binpath_default     = os.path.dirname(which("varnishstat")) + "/"
  File "/usr/lib64/python2.6/posixpath.py", line 119, in dirname
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
[root@mahoning ~]#

[root@vip ~]# python varnishtuner.py
Traceback (most recent call last):
  File "varnishtuner.py", line 539, in <module>
    SCI = ServerCPUInfo()
  File "varnishtuner.py", line 96, in **init**
    self.have_ht = self.haveHT()
  File "varnishtuner.py", line 139, in haveHT
    if self.numberHT() == self.numberCores():
  File "varnishtuner.py", line 128, in numberCores
    nr_cpus = self.numberCPUs()
  File "varnishtuner.py", line 123, in numberCPUs
    return int(cpu_d['physical id']) + 1
  File "varnishtuner.py", line 61, in **getitem**
    val = dict.**getitem**(self, key)
KeyError: 'physical id'
[root@vip ~]#

**Comment by unixy** [comment]
Issue you're having on server 'vip' should be fixed in master now. On 'mahoning', perhaps you don't have Varnish installed or is installed in a non-shell visible location? If so, use this to tell the tuner script where to find it:

python varnishtuner.py -b /path/to/your/varnish/directory/
